import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import Header from './Header';
import Footer from './Footer';
import { 
  Calendar, Clock, MapPin, Ticket, CheckCircle2, Download, 
  Mail, User, QrCode, Copy, Check, Loader2
} from 'lucide-react';
import { usePurchase } from '../context/PurchaseContext';

/**
 * TEMPORARY/MOCK QR CODE
 * 
 * This QR code is a placeholder for UI preview purposes only.
 * Real QR codes are generated by the backend webhook handler
 * after Stripe payment confirmation (payment_intent.succeeded).
 * 
 * In production:
 * - Frontend fetches real tickets from: GET /api/orders/{orderId}/tickets
 * - Each ticket has a unique qr_code and qr_code_data (base64 image)
 * - One unique QR code per ticket entry or seat
 */

// QR Code SVG as base64 for PDF (TEMPORARY - replaced by backend QR in production)
const generateQRCodeDataUrl = () => {
  const svgString = `
    <svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" viewBox="0 0 120 120">
      <rect width="120" height="120" fill="white"/>
      <rect x="8" y="8" width="28" height="28" fill="black"/>
      <rect x="12" y="12" width="20" height="20" fill="white"/>
      <rect x="16" y="16" width="12" height="12" fill="black"/>
      <rect x="84" y="8" width="28" height="28" fill="black"/>
      <rect x="88" y="12" width="20" height="20" fill="white"/>
      <rect x="92" y="16" width="12" height="12" fill="black"/>
      <rect x="8" y="84" width="28" height="28" fill="black"/>
      <rect x="12" y="88" width="20" height="20" fill="white"/>
      <rect x="16" y="92" width="12" height="12" fill="black"/>
      <rect x="44" y="8" width="8" height="8" fill="black"/>
      <rect x="56" y="8" width="8" height="8" fill="black"/>
      <rect x="68" y="8" width="8" height="8" fill="black"/>
      <rect x="44" y="20" width="8" height="8" fill="black"/>
      <rect x="60" y="20" width="8" height="8" fill="black"/>
      <rect x="8" y="44" width="8" height="8" fill="black"/>
      <rect x="20" y="44" width="8" height="8" fill="black"/>
      <rect x="8" y="56" width="8" height="8" fill="black"/>
      <rect x="24" y="56" width="8" height="8" fill="black"/>
      <rect x="8" y="68" width="8" height="8" fill="black"/>
      <rect x="20" y="68" width="8" height="8" fill="black"/>
      <rect x="44" y="44" width="8" height="8" fill="black"/>
      <rect x="56" y="44" width="8" height="8" fill="black"/>
      <rect x="68" y="44" width="8" height="8" fill="black"/>
      <rect x="48" y="52" width="8" height="8" fill="black"/>
      <rect x="64" y="52" width="8" height="8" fill="black"/>
      <rect x="44" y="60" width="8" height="8" fill="black"/>
      <rect x="60" y="60" width="8" height="8" fill="black"/>
      <rect x="52" y="68" width="8" height="8" fill="black"/>
      <rect x="68" y="68" width="8" height="8" fill="black"/>
      <rect x="84" y="44" width="8" height="8" fill="black"/>
      <rect x="96" y="44" width="8" height="8" fill="black"/>
      <rect x="104" y="44" width="8" height="8" fill="black"/>
      <rect x="88" y="56" width="8" height="8" fill="black"/>
      <rect x="104" y="56" width="8" height="8" fill="black"/>
      <rect x="84" y="68" width="8" height="8" fill="black"/>
      <rect x="100" y="68" width="8" height="8" fill="black"/>
      <rect x="44" y="84" width="8" height="8" fill="black"/>
      <rect x="60" y="84" width="8" height="8" fill="black"/>
      <rect x="72" y="84" width="8" height="8" fill="black"/>
      <rect x="52" y="92" width="8" height="8" fill="black"/>
      <rect x="68" y="92" width="8" height="8" fill="black"/>
      <rect x="84" y="92" width="8" height="8" fill="black"/>
      <rect x="44" y="100" width="8" height="8" fill="black"/>
      <rect x="56" y="100" width="8" height="8" fill="black"/>
      <rect x="76" y="100" width="8" height="8" fill="black"/>
      <rect x="92" y="100" width="8" height="8" fill="black"/>
      <rect x="104" y="100" width="8" height="8" fill="black"/>
    </svg>
  `;
  return 'data:image/svg+xml;base64,' + btoa(svgString);
};

// Generate PDF Ticket
const generateTicketPDF = (data) => {
  const { event, selectedFunction, tickets, seats, buyer, total, currency, orderId } = data;
  const isSeatedEvent = seats && seats.length > 0;
  
  // Create PDF (A4 size)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  // Colors
  const primaryBlue = [0, 122, 255];
  const accentOrange = [255, 149, 0];
  const darkBg = [18, 18, 18];
  const white = [255, 255, 255];
  const gray = [150, 150, 150];
  
  // Background
  doc.setFillColor(...darkBg);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Header stripe
  doc.setFillColor(...primaryBlue);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  // Logo text (since we can't load external images easily)
  doc.setTextColor(...white);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('PRONTO', margin, 22);
  doc.setTextColor(...accentOrange);
  doc.text('TICKET', margin + 52, 22);
  doc.setTextColor(...white);
  doc.setFontSize(12);
  doc.text('LIVE', margin + 85, 22);
  
  // Tagline
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255, 0.8);
  doc.text('Fácil, Rápido y Seguro', margin, 35);
  
  // Ticket title
  let yPos = 60;
  doc.setFontSize(12);
  doc.setTextColor(...gray);
  doc.text('ENTRADA ELECTRÓNICA', margin, yPos);
  
  // Event name
  yPos += 12;
  doc.setFontSize(22);
  doc.setTextColor(...white);
  doc.setFont('helvetica', 'bold');
  
  // Handle long event names
  const eventTitle = event.title || 'Evento';
  const splitTitle = doc.splitTextToSize(eventTitle, contentWidth);
  doc.text(splitTitle, margin, yPos);
  yPos += (splitTitle.length * 8) + 5;
  
  // Divider line
  doc.setDrawColor(...primaryBlue);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 15;
  
  // Event details section
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('FECHA Y HORA', margin, yPos);
  yPos += 6;
  doc.setFontSize(14);
  doc.setTextColor(...white);
  doc.setFont('helvetica', 'normal');
  const eventDate = selectedFunction?.date || event.date || 'Por confirmar';
  const eventTime = selectedFunction?.time || event.time || '';
  doc.text(`${eventDate} - ${eventTime} hrs`, margin, yPos);
  
  // Venue (right side)
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('LUGAR', pageWidth / 2 + 10, yPos - 6);
  doc.setFontSize(14);
  doc.setTextColor(...white);
  const venue = event.venue || 'Por confirmar';
  const city = event.city || '';
  doc.text(venue, pageWidth / 2 + 10, yPos);
  yPos += 6;
  doc.setFontSize(11);
  doc.setTextColor(...gray);
  doc.text(city, pageWidth / 2 + 10, yPos);
  
  yPos += 20;
  
  // Tickets/Seats section
  doc.setDrawColor(50, 50, 50);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('ENTRADAS', margin, yPos);
  yPos += 8;
  
  doc.setFontSize(12);
  doc.setTextColor(...white);
  doc.setFont('helvetica', 'normal');
  
  if (isSeatedEvent) {
    seats.forEach((seat, index) => {
      const seatInfo = `${seat.section || 'Sección'} - Fila ${seat.row || '-'}, Asiento ${seat.number || seat.seat || '-'}`;
      doc.text(seatInfo, margin, yPos);
      yPos += 7;
    });
  } else if (tickets && tickets.length > 0) {
    tickets.filter(t => t.quantity > 0).forEach((ticket, index) => {
      const ticketInfo = `${ticket.type || ticket.name || 'General'} x ${ticket.quantity}`;
      doc.text(ticketInfo, margin, yPos);
      yPos += 7;
    });
  }
  
  yPos += 10;
  
  // Order info and buyer section
  doc.setDrawColor(50, 50, 50);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  // Left column - Order info
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('NÚMERO DE ORDEN', margin, yPos);
  yPos += 6;
  doc.setFontSize(14);
  doc.setTextColor(...accentOrange);
  doc.setFont('helvetica', 'bold');
  doc.text(orderId || 'N/A', margin, yPos);
  
  // Right column - Buyer info
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('COMPRADOR', pageWidth / 2 + 10, yPos - 6);
  doc.setFontSize(12);
  doc.setTextColor(...white);
  doc.setFont('helvetica', 'normal');
  const buyerName = `${buyer?.firstName || ''} ${buyer?.lastName || ''}`.trim() || 'N/A';
  doc.text(buyerName, pageWidth / 2 + 10, yPos);
  
  yPos += 20;
  
  // Total section
  doc.setDrawColor(50, 50, 50);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text('TOTAL PAGADO', margin, yPos);
  yPos += 8;
  doc.setFontSize(20);
  doc.setTextColor(...accentOrange);
  doc.setFont('helvetica', 'bold');
  const currencySymbol = currency?.symbol || '$';
  const totalFormatted = total ? `${currencySymbol}${total.toLocaleString()}` : 'N/A';
  doc.text(totalFormatted, margin, yPos);
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text(currency?.code || 'MXN', margin + 50, yPos);
  
  // QR Code section (bottom)
  yPos = pageHeight - 90;
  
  // QR Code box
  const qrSize = 50;
  const qrX = (pageWidth - qrSize) / 2;
  
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(qrX - 5, yPos - 5, qrSize + 10, qrSize + 10, 3, 3, 'F');
  
  // Draw QR pattern manually (simplified version)
  doc.setFillColor(0, 0, 0);
  const qrScale = qrSize / 120;
  const qrPatterns = [
    // Position detection patterns
    [8, 8, 28, 28], [84, 8, 28, 28], [8, 84, 28, 28],
    // Data modules (simplified)
    [44, 8, 8, 8], [56, 8, 8, 8], [68, 8, 8, 8],
    [44, 44, 8, 8], [56, 44, 8, 8], [68, 44, 8, 8],
    [44, 84, 8, 8], [60, 84, 8, 8], [84, 92, 8, 8]
  ];
  
  qrPatterns.forEach(([x, y, w, h]) => {
    doc.rect(qrX + (x * qrScale), yPos + (y * qrScale), w * qrScale, h * qrScale, 'F');
  });
  
  // Inner white squares for position patterns
  doc.setFillColor(255, 255, 255);
  [[12, 12, 20, 20], [88, 12, 20, 20], [12, 88, 20, 20]].forEach(([x, y, w, h]) => {
    doc.rect(qrX + (x * qrScale), yPos + (y * qrScale), w * qrScale, h * qrScale, 'F');
  });
  
  // Inner black squares
  doc.setFillColor(0, 0, 0);
  [[16, 16, 12, 12], [92, 16, 12, 12], [16, 92, 12, 12]].forEach(([x, y, w, h]) => {
    doc.rect(qrX + (x * qrScale), yPos + (y * qrScale), w * qrScale, h * qrScale, 'F');
  });
  
  // QR instruction text
  yPos += qrSize + 15;
  doc.setFontSize(10);
  doc.setTextColor(...white);
  doc.setFont('helvetica', 'normal');
  const qrText = 'Presenta este código QR en la entrada del evento';
  const textWidth = doc.getTextWidth(qrText);
  doc.text(qrText, (pageWidth - textWidth) / 2, yPos);
  
  // Footer
  yPos = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(...gray);
  const footerText = 'Este boleto es personal e intransferible. ProntoTicketLive © 2025';
  const footerWidth = doc.getTextWidth(footerText);
  doc.text(footerText, (pageWidth - footerWidth) / 2, yPos);
  
  return doc;
};

const ConfirmationPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { clearPurchase, formatPrice } = usePurchase();
  
  const [confirmationData, setConfirmationData] = useState(null);
  const [copied, setCopied] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  // Load confirmation data from sessionStorage
  useEffect(() => {
    const stored = sessionStorage.getItem('prontoticket_confirmation');
    if (stored) {
      try {
        const data = JSON.parse(stored);
        setConfirmationData(data);
        // Clear purchase state after successful confirmation
        clearPurchase();
      } catch (e) {
        console.error('Failed to parse confirmation data:', e);
        navigate('/');
      }
    } else {
      // No confirmation data, redirect to home
      navigate('/');
    }
  }, [clearPurchase, navigate]);

  const handleCopyOrderId = () => {
    if (confirmationData?.orderId) {
      navigator.clipboard.writeText(confirmationData.orderId);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadTickets = async () => {
    if (!confirmationData || isGeneratingPDF) return;
    
    setIsGeneratingPDF(true);
    
    try {
      // Small delay for UX feedback
      await new Promise(resolve => setTimeout(resolve, 500));
      
      // Generate PDF
      const doc = generateTicketPDF(confirmationData);
      
      // Generate filename
      const eventName = (confirmationData.event?.title || 'Ticket')
        .replace(/[^a-zA-Z0-9]/g, '_')
        .substring(0, 30);
      const orderId = confirmationData.orderId || 'ticket';
      const filename = `ProntoTicket_${eventName}_${orderId}.pdf`;
      
      // Download PDF
      doc.save(filename);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error al generar el ticket. Por favor, intenta de nuevo.');
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleBackToHome = () => {
    // Clear confirmation data
    sessionStorage.removeItem('prontoticket_confirmation');
    navigate('/');
  };

  if (!confirmationData) {
    return (
      <div className="min-h-screen bg-[#0A0A0A] flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#007AFF]"></div>
      </div>
    );
  }

  const { event, selectedFunction, tickets, seats, buyer, total, currency, orderId } = confirmationData;
  const isSeatedEvent = seats && seats.length > 0;

  return (
    <div className="min-h-screen bg-[#0A0A0A]" data-testid="confirmation-page">
      <Header />

      <div className="pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Success Header */}
          <div className="text-center mb-10">
            <div className="w-20 h-20 rounded-full bg-green-500/20 flex items-center justify-center mx-auto mb-6">
              <CheckCircle2 size={48} className="text-green-500" />
            </div>
            <h1 
              className="text-3xl sm:text-4xl md:text-5xl font-bold text-white tracking-tight mb-3"
              style={{ fontFamily: "'Outfit', sans-serif" }}
              data-testid="page-title"
            >
              ¡Compra exitosa!
            </h1>
            <p className="text-white/60 text-base sm:text-lg">
              Tu pedido ha sido confirmado. Recibirás un email con los detalles.
            </p>
          </div>

          {/* Order ID */}
          <div className="bg-[#121212] rounded-2xl border border-white/10 p-5 sm:p-6 mb-6" data-testid="order-id-card">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-white/50 text-xs uppercase tracking-wide mb-1">Número de orden</p>
                <p className="text-white font-bold text-lg sm:text-xl font-mono" data-testid="order-id">
                  {orderId}
                </p>
              </div>
              <button
                onClick={handleCopyOrderId}
                className="p-2.5 bg-white/5 hover:bg-white/10 rounded-lg transition-colors flex items-center space-x-2"
                title="Copiar número de orden"
              >
                {copied ? (
                  <Check size={18} className="text-green-500" />
                ) : (
                  <Copy size={18} className="text-white/60" />
                )}
              </button>
            </div>
          </div>

          {/* Event Details */}
          <div className="bg-[#121212] rounded-2xl border border-white/10 p-5 sm:p-6 mb-6" data-testid="event-details-card">
            <h2 
              className="text-lg font-bold text-white mb-4 tracking-tight"
              style={{ fontFamily: "'Outfit', sans-serif" }}
            >
              Detalles del evento
            </h2>

            <div className="flex gap-4">
              {/* QR Code for Event Details */}
              <div className="w-24 h-24 bg-white rounded-xl flex items-center justify-center flex-shrink-0 p-1.5" data-testid="event-qr-code">
                <svg 
                  width="80" 
                  height="80" 
                  viewBox="0 0 120 120" 
                  className="w-full h-full"
                >
                  <rect width="120" height="120" fill="white"/>
                  {/* Position detection patterns */}
                  <rect x="8" y="8" width="28" height="28" fill="black"/>
                  <rect x="12" y="12" width="20" height="20" fill="white"/>
                  <rect x="16" y="16" width="12" height="12" fill="black"/>
                  
                  <rect x="84" y="8" width="28" height="28" fill="black"/>
                  <rect x="88" y="12" width="20" height="20" fill="white"/>
                  <rect x="92" y="16" width="12" height="12" fill="black"/>
                  
                  <rect x="8" y="84" width="28" height="28" fill="black"/>
                  <rect x="12" y="88" width="20" height="20" fill="white"/>
                  <rect x="16" y="92" width="12" height="12" fill="black"/>
                  
                  {/* Data modules */}
                  <rect x="44" y="8" width="8" height="8" fill="black"/>
                  <rect x="56" y="8" width="8" height="8" fill="black"/>
                  <rect x="68" y="8" width="8" height="8" fill="black"/>
                  <rect x="44" y="20" width="8" height="8" fill="black"/>
                  <rect x="60" y="20" width="8" height="8" fill="black"/>
                  <rect x="8" y="44" width="8" height="8" fill="black"/>
                  <rect x="20" y="44" width="8" height="8" fill="black"/>
                  <rect x="8" y="56" width="8" height="8" fill="black"/>
                  <rect x="24" y="56" width="8" height="8" fill="black"/>
                  <rect x="8" y="68" width="8" height="8" fill="black"/>
                  <rect x="20" y="68" width="8" height="8" fill="black"/>
                  <rect x="44" y="44" width="8" height="8" fill="black"/>
                  <rect x="56" y="44" width="8" height="8" fill="black"/>
                  <rect x="68" y="44" width="8" height="8" fill="black"/>
                  <rect x="48" y="52" width="8" height="8" fill="black"/>
                  <rect x="64" y="52" width="8" height="8" fill="black"/>
                  <rect x="44" y="60" width="8" height="8" fill="black"/>
                  <rect x="60" y="60" width="8" height="8" fill="black"/>
                  <rect x="52" y="68" width="8" height="8" fill="black"/>
                  <rect x="68" y="68" width="8" height="8" fill="black"/>
                  <rect x="84" y="44" width="8" height="8" fill="black"/>
                  <rect x="96" y="44" width="8" height="8" fill="black"/>
                  <rect x="104" y="44" width="8" height="8" fill="black"/>
                  <rect x="88" y="56" width="8" height="8" fill="black"/>
                  <rect x="104" y="56" width="8" height="8" fill="black"/>
                  <rect x="84" y="68" width="8" height="8" fill="black"/>
                  <rect x="100" y="68" width="8" height="8" fill="black"/>
                  <rect x="44" y="84" width="8" height="8" fill="black"/>
                  <rect x="60" y="84" width="8" height="8" fill="black"/>
                  <rect x="72" y="84" width="8" height="8" fill="black"/>
                  <rect x="52" y="92" width="8" height="8" fill="black"/>
                  <rect x="68" y="92" width="8" height="8" fill="black"/>
                  <rect x="84" y="92" width="8" height="8" fill="black"/>
                  <rect x="44" y="100" width="8" height="8" fill="black"/>
                  <rect x="56" y="100" width="8" height="8" fill="black"/>
                  <rect x="76" y="100" width="8" height="8" fill="black"/>
                  <rect x="92" y="100" width="8" height="8" fill="black"/>
                  <rect x="104" y="100" width="8" height="8" fill="black"/>
                  <rect x="44" y="32" width="8" height="4" fill="black"/>
                  <rect x="60" y="32" width="8" height="4" fill="black"/>
                  <rect x="32" y="44" width="4" height="8" fill="black"/>
                  <rect x="32" y="60" width="4" height="8" fill="black"/>
                </svg>
              </div>
              <div className="flex-1">
                <h3 className="text-white font-bold text-base sm:text-lg mb-2">{event.title}</h3>
                <div className="space-y-1.5">
                  <div className="flex items-center space-x-2 text-sm text-white/70">
                    <Calendar size={14} className="text-[#007AFF]" />
                    <span>{selectedFunction?.date || event.date}</span>
                  </div>
                  <div className="flex items-center space-x-2 text-sm text-white/70">
                    <Clock size={14} className="text-[#FF9500]" />
                    <span>{selectedFunction?.time || event.time} hrs</span>
                  </div>
                  <div className="flex items-center space-x-2 text-sm text-white/70">
                    <MapPin size={14} className="text-[#007AFF]" />
                    <a
                      href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${event.venue}, ${event.city}`)}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-[#007AFF] transition-colors duration-200"
                      title="Abrir en Google Maps"
                      data-testid="venue-maps-link"
                    >
                      {event.venue}, {event.city}
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Tickets */}
          <div className="bg-[#121212] rounded-2xl border border-white/10 p-5 sm:p-6 mb-6" data-testid="tickets-card">
            <div className="flex items-center space-x-2 mb-4">
              <Ticket size={18} className="text-[#007AFF]" />
              <h2 className="text-lg font-bold text-white tracking-tight" style={{ fontFamily: "'Outfit', sans-serif" }}>
                Tus entradas
              </h2>
            </div>

            <div className="space-y-3">
              {isSeatedEvent ? (
                seats.map((seat, index) => (
                  <div key={seat.id || index} className="p-4 bg-[#1E1E1E] rounded-xl border border-white/5">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="text-white font-semibold">Asiento {seat.number || seat.seat}</p>
                        <p className="text-white/60 text-sm">{seat.section} - Fila {seat.row}</p>
                      </div>
                      <span className="text-[#FF9500] font-bold">{formatPrice(seat.price)}</span>
                    </div>
                  </div>
                ))
              ) : (
                tickets?.filter(t => t.quantity > 0).map((ticket, index) => (
                  <div key={ticket.id || index} className="p-4 bg-[#1E1E1E] rounded-xl border border-white/5">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="text-white font-semibold">{ticket.type || ticket.name}</p>
                        <p className="text-white/60 text-sm">Cantidad: {ticket.quantity}</p>
                      </div>
                      <span className="text-[#FF9500] font-bold">{formatPrice(ticket.price * ticket.quantity)}</span>
                    </div>
                  </div>
                ))
              )}
            </div>

            {/* QR Code Section */}
            <div className="mt-6 pt-6 border-t border-white/10">
              <div className="flex flex-col items-center">
                {/* Mock QR Code */}
                <div className="bg-white p-3 rounded-xl mb-3" data-testid="ticket-qr-code">
                  <svg 
                    width="120" 
                    height="120" 
                    viewBox="0 0 120 120" 
                    className="w-28 h-28 sm:w-32 sm:h-32"
                  >
                    {/* QR Code Pattern - Mock visual */}
                    <rect width="120" height="120" fill="white"/>
                    {/* Position detection patterns (corners) */}
                    <rect x="8" y="8" width="28" height="28" fill="black"/>
                    <rect x="12" y="12" width="20" height="20" fill="white"/>
                    <rect x="16" y="16" width="12" height="12" fill="black"/>
                    
                    <rect x="84" y="8" width="28" height="28" fill="black"/>
                    <rect x="88" y="12" width="20" height="20" fill="white"/>
                    <rect x="92" y="16" width="12" height="12" fill="black"/>
                    
                    <rect x="8" y="84" width="28" height="28" fill="black"/>
                    <rect x="12" y="88" width="20" height="20" fill="white"/>
                    <rect x="16" y="92" width="12" height="12" fill="black"/>
                    
                    {/* Data modules - random pattern for mock */}
                    <rect x="44" y="8" width="8" height="8" fill="black"/>
                    <rect x="56" y="8" width="8" height="8" fill="black"/>
                    <rect x="68" y="8" width="8" height="8" fill="black"/>
                    
                    <rect x="44" y="20" width="8" height="8" fill="black"/>
                    <rect x="60" y="20" width="8" height="8" fill="black"/>
                    
                    <rect x="8" y="44" width="8" height="8" fill="black"/>
                    <rect x="20" y="44" width="8" height="8" fill="black"/>
                    <rect x="8" y="56" width="8" height="8" fill="black"/>
                    <rect x="24" y="56" width="8" height="8" fill="black"/>
                    <rect x="8" y="68" width="8" height="8" fill="black"/>
                    <rect x="20" y="68" width="8" height="8" fill="black"/>
                    
                    {/* Center area data */}
                    <rect x="44" y="44" width="8" height="8" fill="black"/>
                    <rect x="56" y="44" width="8" height="8" fill="black"/>
                    <rect x="68" y="44" width="8" height="8" fill="black"/>
                    <rect x="48" y="52" width="8" height="8" fill="black"/>
                    <rect x="64" y="52" width="8" height="8" fill="black"/>
                    <rect x="44" y="60" width="8" height="8" fill="black"/>
                    <rect x="60" y="60" width="8" height="8" fill="black"/>
                    <rect x="52" y="68" width="8" height="8" fill="black"/>
                    <rect x="68" y="68" width="8" height="8" fill="black"/>
                    
                    {/* Right side data */}
                    <rect x="84" y="44" width="8" height="8" fill="black"/>
                    <rect x="96" y="44" width="8" height="8" fill="black"/>
                    <rect x="104" y="44" width="8" height="8" fill="black"/>
                    <rect x="88" y="56" width="8" height="8" fill="black"/>
                    <rect x="104" y="56" width="8" height="8" fill="black"/>
                    <rect x="84" y="68" width="8" height="8" fill="black"/>
                    <rect x="100" y="68" width="8" height="8" fill="black"/>
                    
                    {/* Bottom area data */}
                    <rect x="44" y="84" width="8" height="8" fill="black"/>
                    <rect x="60" y="84" width="8" height="8" fill="black"/>
                    <rect x="72" y="84" width="8" height="8" fill="black"/>
                    <rect x="52" y="92" width="8" height="8" fill="black"/>
                    <rect x="68" y="92" width="8" height="8" fill="black"/>
                    <rect x="84" y="92" width="8" height="8" fill="black"/>
                    <rect x="44" y="100" width="8" height="8" fill="black"/>
                    <rect x="56" y="100" width="8" height="8" fill="black"/>
                    <rect x="76" y="100" width="8" height="8" fill="black"/>
                    <rect x="92" y="100" width="8" height="8" fill="black"/>
                    <rect x="104" y="100" width="8" height="8" fill="black"/>
                    
                    {/* Timing patterns */}
                    <rect x="44" y="32" width="8" height="4" fill="black"/>
                    <rect x="60" y="32" width="8" height="4" fill="black"/>
                    <rect x="32" y="44" width="4" height="8" fill="black"/>
                    <rect x="32" y="60" width="4" height="8" fill="black"/>
                  </svg>
                </div>
                
                {/* QR Instructions */}
                <p className="text-white/60 text-xs sm:text-sm text-center max-w-xs">
                  Presenta este código QR en la entrada del evento
                </p>
                
                {/* Order reference under QR */}
                <p className="text-white/40 text-xs mt-2 font-mono">
                  {orderId}
                </p>
              </div>
            </div>

            {/* Total */}
            <div className="mt-4 pt-4 border-t border-white/10 flex justify-between items-baseline">
              <span className="text-white font-bold">Total pagado</span>
              <div className="text-right">
                <div className="text-2xl font-bold text-[#FF9500]" style={{ fontFamily: "'Outfit', sans-serif" }}>
                  {formatPrice(total)}
                </div>
                <div className="text-white/40 text-xs">{currency?.code || 'MXN'}</div>
              </div>
            </div>
          </div>

          {/* Buyer Info */}
          <div className="bg-[#121212] rounded-2xl border border-white/10 p-5 sm:p-6 mb-6" data-testid="buyer-card">
            <div className="flex items-center space-x-2 mb-4">
              <User size={18} className="text-[#007AFF]" />
              <h2 className="text-lg font-bold text-white tracking-tight" style={{ fontFamily: "'Outfit', sans-serif" }}>
                Datos del comprador
              </h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <p className="text-white/50 text-xs uppercase tracking-wide mb-1">Nombre</p>
                <p className="text-white font-medium">{buyer.firstName} {buyer.lastName}</p>
              </div>
              <div>
                <p className="text-white/50 text-xs uppercase tracking-wide mb-1">Email</p>
                <p className="text-white font-medium">{buyer.email}</p>
              </div>
              <div>
                <p className="text-white/50 text-xs uppercase tracking-wide mb-1">Teléfono</p>
                <p className="text-white font-medium">{buyer.phone}</p>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="space-y-4">
            <button
              onClick={handleDownloadTickets}
              disabled={isGeneratingPDF}
              className="w-full py-4 bg-gradient-to-r from-[#007AFF] to-[#0056b3] text-white font-bold rounded-full transition-all duration-300 hover:brightness-110 shadow-lg flex items-center justify-center space-x-2 disabled:opacity-70 disabled:cursor-wait"
              data-testid="download-tickets-button"
            >
              {isGeneratingPDF ? (
                <>
                  <Loader2 size={18} className="animate-spin" />
                  <span>Generando ticket...</span>
                </>
              ) : (
                <>
                  <Download size={18} />
                  <span>Descargar entradas</span>
                </>
              )}
            </button>

            <div className="flex items-center justify-center space-x-2 text-white/60 text-sm">
              <Mail size={14} />
              <span>También enviamos las entradas a tu correo electrónico</span>
            </div>

            <button
              onClick={handleBackToHome}
              className="w-full py-3 text-white/70 hover:text-white font-semibold transition-colors text-sm"
              data-testid="back-to-home-button"
            >
              Volver al inicio
            </button>
          </div>

        </div>
      </div>

      <Footer />
    </div>
  );
};

export default ConfirmationPage;
